last_change = 2026-09-10T18:38:12.904506Z
addr = 0x14f2d0
size = 0x3
name = "IGameSystem_OnBuildGameSessionManifest"

[header]
name = "IGameSystem_OnBuildGameSessionManifest"
addr = 0x14f2d0

[header.args]
