last_change = 2026-09-10T18:38:12.904626Z
addr = 0x159e70
size = 0x3
name = "IGameSystem_OnServerPreClientUpdate"

[header]
name = "IGameSystem_OnServerPreClientUpdate"
addr = 0x159e70

[header.args]
