last_change = 2026-09-10T18:38:12.904600Z
addr = 0x159d80
size = 0x3
name = "CCSPlayerPawn_OnTakeDamage_Dead"
type = "void"

[header]
name = "CCSPlayerPawn_OnTakeDamage_Dead"
addr = 0x159d80
type = "void"

[header.args]
