last_change = 2026-09-10T18:38:12.904578Z
addr = 0x159cf0
size = 0x3
name = "IGameSystem_OnServerPreEndAsyncPostTickWork"

[header]
name = "IGameSystem_OnServerPreEndAsyncPostTickWork"
addr = 0x159cf0

[header.args]
