last_change = 2026-09-10T18:38:12.904538Z
addr = 0x1520e0
size = 0x9
name = "CBaseEntity_GetChangeAccessorPathInfo_2"
type = "long long"

[header]
name = "CBaseEntity_GetChangeAccessorPathInfo_2"
addr = 0x1520e0
type = "long long"

[header.args]
