last_change = 2026-09-10T18:38:12.904671Z
addr = 0x18f370
size = 0x3
name = "CGameSceneNode_GetSkeletonInstance"
type = "long long"

[header]
name = "CGameSceneNode_GetSkeletonInstance"
addr = 0x18f370
type = "long long"

[header.args]
