last_change = 2026-09-10T18:38:24.239944Z
addr = 0x1ad310
size = 0x5d5
name = "CNetworkTransmitComponent_StateChanged"
type = "void"

[header]
name = "CNetworkTransmitComponent_StateChanged"
addr = 0x1ad310
type = "void"

[header.args]
