last_change = 2026-09-10T18:38:12.904683Z
addr = 0x1b3630
size = 0x921
name = "CSource2Server_ApplyGameSettings"
type = "void"

[header]
name = "CSource2Server_ApplyGameSettings"
addr = 0x1b3630
type = "void"

[header.args]
