last_change = 2026-09-10T18:38:12.904689Z
addr = 0x1b6bc0
size = 0xf9
name = "CSource2Server_GetMatchmakingGameData"
type = "unsigned int"

[header]
name = "CSource2Server_GetMatchmakingGameData"
addr = 0x1b6bc0
type = "unsigned int"

[header.args]
