last_change = 2026-09-10T18:38:12.904711Z
addr = 0x1c9bf0
size = 0x2ff
name = "CCSPlayerPawn_CreatePlayerPawnServices"
type = "char"

[header]
name = "CCSPlayerPawn_CreatePlayerPawnServices"
addr = 0x1c9bf0
type = "char"

[header.args]
