last_change = 2026-09-10T18:38:12.904744Z
addr = 0x1e5080
size = 0xad4
name = "CCSPlayerPawn_ProcessSuicideAsKillReward"
type = "void"

[header]
name = "CCSPlayerPawn_ProcessSuicideAsKillReward"
addr = 0x1e5080
type = "void"

[header.args]
