last_change = 2026-09-10T18:38:12.904728Z
addr = 0x1e0e30
size = 0x4d7
name = "CNetworkUtlVectorEmbedded_NetworkStateChanged_m_perRoundStats"
type = "void"

[header]
name = "CNetworkUtlVectorEmbedded_NetworkStateChanged_m_perRoundStats"
addr = 0x1e0e30
type = "void"

[header.args]
