last_change = 2026-09-10T18:38:24.977931Z
addr = 0x268540
size = 0x2de
name = "ScriptBinding_Entity_SetEntityName"
type = "void"

[header]
name = "ScriptBinding_Entity_SetEntityName"
addr = 0x268540
type = "void"

[header.args]
