last_change = 2026-09-10T18:38:12.904821Z
addr = 0x2b7f60
size = 0x705
name = "CCSBotManager_BotPlaceCommand"
type = "char"

[header]
name = "CCSBotManager_BotPlaceCommand"
addr = 0x2b7f60
type = "char"

[header.args]
