last_change = 2026-09-10T18:38:12.904837Z
addr = 0x2c9d50
size = 0x15
name = "CCSBot_InhibitLookAround"
type = "void *"

[header]
name = "CCSBot_InhibitLookAround"
addr = 0x2c9d50
type = "void *"

[header.args]
