last_change = 2026-09-10T18:38:25.788871Z
addr = 0x2ea740
size = 0x384
name = "BotKill_CommandHandler"
type = "void"

[header]
name = "BotKill_CommandHandler"
addr = 0x2ea740
type = "void"

[header.args]
