last_change = 2026-09-10T18:38:12.904887Z
addr = 0x3071c0
size = 0x695
name = "CBtActionCoordinatedBuy_Update"
type = "long long"

[header]
name = "CBtActionCoordinatedBuy_Update"
addr = 0x3071c0
type = "long long"

[header.args]
