last_change = 2026-09-10T18:38:12.904898Z
addr = 0x341c60
size = 0x429
name = "CChicken_Event_Killed"
type = "long long"

[header]
name = "CChicken_Event_Killed"
addr = 0x341c60
type = "long long"

[header.args]
