last_change = 2026-09-10T18:38:12.904942Z
addr = 0x3cc6a0
size = 0xda
name = "CBaseEntity_GetAbsVelocity"
type = "long long"

[header]
name = "CBaseEntity_GetAbsVelocity"
addr = 0x3cc6a0
type = "long long"

[header.args]
