last_change = 2026-09-10T18:38:12.904937Z
addr = 0x3cc4d0
size = 0x2c
name = "CBaseEntity_GetAbsAngles"
type = "long long"

[header]
name = "CBaseEntity_GetAbsAngles"
addr = 0x3cc4d0
type = "long long"

[header.args]
