last_change = 2026-09-10T18:38:12.904965Z
addr = 0x3daac0
size = 0x219
name = "CBaseTrigger_PassesTriggerFilters"
type = "char"

[header]
name = "CBaseTrigger_PassesTriggerFilters"
addr = 0x3daac0
type = "char"

[header.args]
