last_change = 2026-09-10T18:38:26.827503Z
addr = 0x3e4660
size = 0x745
name = "CBaseEntity_TakeDamageOld"
type = "unsigned long long"

[header]
name = "CBaseEntity_TakeDamageOld"
addr = 0x3e4660
type = "unsigned long long"

[header.args]
