last_change = 2026-09-10T18:38:12.905022Z
addr = 0x50dd60
size = 0x5f9
name = "DecalPlacementInfo_ctor"
type = "long long *"

[header]
name = "DecalPlacementInfo_ctor"
addr = 0x50dd60
type = "long long *"

[header.args]
