last_change = 2026-09-10T18:38:12.905053Z
addr = 0x529790
size = 0xef
name = "IGameSystem_LoopPreShutdownAllSystems"
type = "long long"

[header]
name = "IGameSystem_LoopPreShutdownAllSystems"
addr = 0x529790
type = "long long"

[header.args]
