last_change = 2026-09-10T18:38:27.338275Z
addr = 0x538ec0
size = 0x3c3
name = "CBodyGameSystem_SpawnDependencyIsland"
type = "int"

[header]
name = "CBodyGameSystem_SpawnDependencyIsland"
addr = 0x538ec0
type = "int"

[header.args]
