last_change = 2026-09-10T18:38:27.295837Z
addr = 0x538dc0
size = 0x4b
name = "IGameSystem_ShutdownAllSystems"
type = "long long"

[header]
name = "IGameSystem_ShutdownAllSystems"
addr = 0x538dc0
type = "long long"

[header.args]
