last_change = 2026-09-10T18:38:12.905078Z
addr = 0x554960
size = 0x229
name = "CSpawnGroupMgrGameSystem_AllocateSpawnGroup"
type = "void"

[header]
name = "CSpawnGroupMgrGameSystem_AllocateSpawnGroup"
addr = 0x554960
type = "void"

[header.args]
