last_change = 2026-09-10T18:38:12.905089Z
addr = 0x55dc60
size = 0xdf
name = "CSpawnGroupMgrGameSystem_CreateLoadingSpawnGroupForSaveFile"
type = "long long"

[header]
name = "CSpawnGroupMgrGameSystem_CreateLoadingSpawnGroupForSaveFile"
addr = 0x55dc60
type = "long long"

[header.args]
