last_change = 2026-09-10T18:38:12.905115Z
addr = 0x58c430
size = 0x2c0
name = "CSpawnGroupMgrGameSystem_ReleaseSpawnGroup"
type = "void"

[header]
name = "CSpawnGroupMgrGameSystem_ReleaseSpawnGroup"
addr = 0x58c430
type = "void"

[header.args]
