last_change = 2026-09-10T18:38:27.803492Z
addr = 0x59b6d0
size = 0x267
name = "CSpawnGroupMgrGameSystem_SetActiveSpawnGroup"
type = "void"

[header]
name = "CSpawnGroupMgrGameSystem_SetActiveSpawnGroup"
addr = 0x59b6d0
type = "void"

[header.args]
