last_change = 2026-09-10T18:38:12.905154Z
addr = 0x5a4a00
size = 0x1d7
name = "CSpawnGroupMgrGameSystem_UnloadSpawnGroup"
type = "void"

[header]
name = "CSpawnGroupMgrGameSystem_UnloadSpawnGroup"
addr = 0x5a4a00
type = "void"

[header.args]
