last_change = 2026-09-10T18:38:12.905149Z
addr = 0x5a0510
size = 0x161
name = "CSpawnGroupMgrGameSystem_SpawnGroupSpawnEntities"
type = "unsigned int *"

[header]
name = "CSpawnGroupMgrGameSystem_SpawnGroupSpawnEntities"
addr = 0x5a0510
type = "unsigned int *"

[header.args]
