last_change = 2026-09-10T18:38:12.905159Z
addr = 0x5ddb90
size = 0x5f0e
name = "CBaseEntity_GetScriptDescInternal"
type = "long long"

[header]
name = "CBaseEntity_GetScriptDescInternal"
addr = 0x5ddb90
type = "long long"

[header.args]
