last_change = 2026-09-10T18:38:12.905351Z
addr = 0x61b860
size = 0x33
name = "CBaseModelEntity_ScriptSetSingleMeshGroup"

[header]
name = "CBaseModelEntity_ScriptSetSingleMeshGroup"
addr = 0x61b860

[header.args]
