last_change = 2026-09-10T18:38:28.228142Z
addr = 0x619cf0
size = 0x2e4
name = "CNetworkUtlVectorEmbedded_TryLateResolve_m_vecRenderAttributes"
type = "char"

[header]
name = "CNetworkUtlVectorEmbedded_TryLateResolve_m_vecRenderAttributes"
addr = 0x619cf0
type = "char"

[header.args]
