last_change = 2026-09-10T18:38:12.905252Z
addr = 0x61b150
size = 0x11
name = "CBaseModelEntity_ScriptGetRenderAlpha"

[header]
name = "CBaseModelEntity_ScriptGetRenderAlpha"
addr = 0x61b150

[header.args]
