last_change = 2026-09-10T18:38:12.905211Z
addr = 0x61ad90
size = 0x16f
name = "CBaseEntity_ScriptGetAttributeFloatValue"

[header]
name = "CBaseEntity_ScriptGetAttributeFloatValue"
addr = 0x61ad90

[header.args]
