last_change = 2026-09-10T18:38:12.905319Z
addr = 0x61b6e0
size = 0x33
name = "CBaseModelEntity_ScriptSetMaterialGroup"

[header]
name = "CBaseModelEntity_ScriptSetMaterialGroup"
addr = 0x61b6e0

[header.args]
