last_change = 2026-09-10T18:38:12.905174Z
addr = 0x616680
size = 0x4e2
name = "CNetworkUtlVectorEmbedded_NetworkStateChanged_m_vecRenderAttributes"
type = "void"

[header]
name = "CNetworkUtlVectorEmbedded_NetworkStateChanged_m_vecRenderAttributes"
addr = 0x616680
type = "void"

[header.args]
