last_change = 2026-09-10T18:38:12.905257Z
addr = 0x61b170
size = 0x3c
name = "CBaseModelEntity_ScriptGetRenderColor"

[header]
name = "CBaseModelEntity_ScriptGetRenderColor"
addr = 0x61b170

[header.args]
