last_change = 2026-09-10T18:38:12.905297Z
addr = 0x61b530
size = 0x11c
name = "CBaseEntity_ScriptSetAttributeIntValue"

[header]
name = "CBaseEntity_ScriptSetAttributeIntValue"
addr = 0x61b530

[header.args]
