last_change = 2026-09-10T18:38:12.905360Z
addr = 0x61b8b0
size = 0x32
name = "CBaseEntity_ScriptTransformPointEntityToWorld"

[header]
name = "CBaseEntity_ScriptTransformPointEntityToWorld"
addr = 0x61b8b0

[header.args]
