last_change = 2026-09-10T18:38:12.905347Z
addr = 0x61b850
size = 0x5
name = "CBaseModelEntity_ScriptSetRenderMode"

[header]
name = "CBaseModelEntity_ScriptSetRenderMode"
addr = 0x61b850

[header.args]
