last_change = 2026-09-10T18:38:12.905342Z
addr = 0x61b790
size = 0xbd
name = "CBaseModelEntity_ScriptSetRenderColor"

[header]
name = "CBaseModelEntity_ScriptSetRenderColor"
addr = 0x61b790

[header.args]
