last_change = 2026-09-10T18:38:12.905243Z
addr = 0x61b0e0
size = 0x5
name = "CBaseModelEntity_ScriptGetMeshGroupMask"

[header]
name = "CBaseModelEntity_ScriptGetMeshGroupMask"
addr = 0x61b0e0

[header.args]
