last_change = 2026-09-10T18:38:30.152802Z
addr = 0x8d6d40
size = 0x59a
name = "PolymorphicHelper_t__SetPolymorphicPointer"
type = "const char *"

[header]
name = "PolymorphicHelper_t__SetPolymorphicPointer"
addr = 0x8d6d40
type = "const char *"

[header.args]
