last_change = 2026-09-10T18:38:12.905388Z
addr = 0x8f90c0
size = 0x42a
name = "CHostage_Follow"
type = "long long"

[header]
name = "CHostage_Follow"
addr = 0x8f90c0
type = "long long"

[header.args]
