last_change = 2026-09-10T18:38:30.280771Z
addr = 0x902a10
size = 0xdbb
name = "CCSGameRules_GoToIntermission"
type = "void"

[header]
name = "CCSGameRules_GoToIntermission"
addr = 0x902a10
type = "void"

[header.args]
