last_change = 2026-09-10T18:38:30.326198Z
addr = 0x914f40
size = 0x4e4
name = "GameSystem_Think_CheckSteamBan"
type = "unsigned int *"

[header]
name = "GameSystem_Think_CheckSteamBan"
addr = 0x914f40
type = "unsigned int *"

[header.args]
