last_change = 2026-09-10T18:38:30.412498Z
addr = 0x93c800
size = 0x16b4
name = "CCSGameRules_TerminateRound"
type = "char *"

[header]
name = "CCSGameRules_TerminateRound"
addr = 0x93c800
type = "char *"

[header.args]
