last_change = 2026-09-10T18:38:30.497090Z
addr = 0x97e940
size = 0x393
name = "SmokeVolume_GetSmokeDensityInLine_Lambda1_operator_call"
type = "char"

[header]
name = "SmokeVolume_GetSmokeDensityInLine_Lambda1_operator_call"
addr = 0x97e940
type = "char"

[header.args]
