last_change = 2026-09-10T18:38:12.905449Z
addr = 0x9e96d0
size = 0x1c7
name = "CBasePlayerWeapon_Shoot_Secondary"
type = "long long"

[header]
name = "CBasePlayerWeapon_Shoot_Secondary"
addr = 0x9e96d0
type = "long long"

[header.args]
