last_change = 2026-09-10T18:38:12.905455Z
addr = 0xa3afe0
size = 0x2fd
name = "CCSPlayerController_ChangeTeam"
type = "_UNKNOWN **"

[header]
name = "CCSPlayerController_ChangeTeam"
addr = 0xa3afe0
type = "_UNKNOWN **"

[header.args]
