last_change = 2026-09-10T18:38:12.905480Z
addr = 0xa510b0
size = 0xc
name = "CCSPlayerController_InventoryUpdateThink"
type = "long long"

[header]
name = "CCSPlayerController_InventoryUpdateThink"
addr = 0xa510b0
type = "long long"

[header.args]
