last_change = 2026-09-10T18:38:12.905496Z
addr = 0xa60500
size = 0x40
name = "CCSPlayerController_HandleCommandDrop"
type = "char"

[header]
name = "CCSPlayerController_HandleCommandDrop"
addr = 0xa60500
type = "char"

[header.args]
