last_change = 2026-09-10T18:38:12.905511Z
addr = 0xa658a0
size = 0x26e
name = "CCSPlayerController_SwitchTeam"
type = "long long"

[header]
name = "CCSPlayerController_SwitchTeam"
addr = 0xa658a0
type = "long long"

[header.args]
