last_change = 2026-09-10T18:38:31.307097Z
addr = 0xa82e20
size = 0x106c
name = "CCSPlayer_ItemServices_CanAcquire"
type = "long long"

[header]
name = "CCSPlayer_ItemServices_CanAcquire"
addr = 0xa82e20
type = "long long"

[header.args]
