last_change = 2026-09-10T18:38:12.905562Z
addr = 0xa91c80
size = 0x28
name = "CCSPlayer_ItemServices_GiveNamedItemBool"
type = "bool"

[header]
name = "CCSPlayer_ItemServices_GiveNamedItemBool"
addr = 0xa91c80
type = "bool"

[header.args]
