last_change = 2026-09-10T18:38:12.905573Z
addr = 0xaa4260
size = 0x2e
name = "CCSPlayerPawn_OnTakeDamage_Alive"
type = "long long"

[header]
name = "CCSPlayerPawn_OnTakeDamage_Alive"
addr = 0xaa4260
type = "long long"

[header.args]
