last_change = 2026-09-10T18:38:12.905598Z
addr = 0xaa9f50
size = 0x155
name = "CCSPlayer_ItemServices_RemoveWeapons"
type = "long long"

[header]
name = "CCSPlayer_ItemServices_RemoveWeapons"
addr = 0xaa9f50
type = "long long"

[header.args]
