last_change = 2026-09-10T18:38:12.905593Z
addr = 0xaa87b0
size = 0x274
name = "CCSPlayerPawn_HandleDropWeapon"
type = "char"

[header]
name = "CCSPlayerPawn_HandleDropWeapon"
addr = 0xaa87b0
type = "char"

[header.args]
