last_change = 2026-09-10T18:38:12.905602Z
addr = 0xab30e0
size = 0x70b
name = "CCSPlayer_UseServices_BumpWeapon"
type = "long long"

[header]
name = "CCSPlayer_UseServices_BumpWeapon"
addr = 0xab30e0
type = "long long"

[header.args]
