last_change = 2026-09-10T18:38:32.074081Z
addr = 0xacf6b0
size = 0x17d
name = "CCSPlayer_WeaponServices_EquipWeapon"
type = "long long"

[header]
name = "CCSPlayer_WeaponServices_EquipWeapon"
addr = 0xacf6b0
type = "long long"

[header.args]
