last_change = 2026-09-10T18:38:12.905612Z
addr = 0xace6f0
size = 0x15c
name = "CCSPlayer_WeaponServices_DropWeapon"
type = "void"

[header]
name = "CCSPlayer_WeaponServices_DropWeapon"
addr = 0xace6f0
type = "void"

[header.args]
