last_change = 2026-09-10T18:38:12.905628Z
addr = 0xad4430
size = 0x39f
name = "CCSPlayer_WeaponServices_HandleDropWeapon"
type = "char"

[header]
name = "CCSPlayer_WeaponServices_HandleDropWeapon"
addr = 0xad4430
type = "char"

[header.args]
