last_change = 2026-09-10T18:38:12.905623Z
addr = 0xad3ae0
size = 0x21e
name = "CTakeDamageInfo_GetWeaponName"
type = "const char *"

[header]
name = "CTakeDamageInfo_GetWeaponName"
addr = 0xad3ae0
type = "const char *"

[header.args]
