last_change = 2026-09-10T18:38:12.905638Z
addr = 0xaece40
size = 0x169
name = "CCSPlayer_WeaponServices_SelectItem"
type = "char"

[header]
name = "CCSPlayer_WeaponServices_SelectItem"
addr = 0xaece40
type = "char"

[header.args]
