last_change = 2026-09-10T18:38:12.905691Z
addr = 0xb19f70
size = 0x5f
name = "CBasePlayerController_GetPawn"
type = "long long"

[header]
name = "CBasePlayerController_GetPawn"
addr = 0xb19f70
type = "long long"

[header.args]
