last_change = 2026-09-10T18:38:12.905653Z
addr = 0xb11930
size = 0x29
name = "CCSPlayerController_Disconnect"
type = "void"

[header]
name = "CCSPlayerController_Disconnect"
addr = 0xb11930
type = "void"

[header.args]
