last_change = 2026-09-10T18:38:12.905663Z
addr = 0xb14c20
size = 0x123
name = "CBasePlayerPawn_GetEyeAngles"
type = "long long"

[header]
name = "CBasePlayerPawn_GetEyeAngles"
addr = 0xb14c20
type = "long long"

[header.args]
