last_change = 2026-09-10T18:38:12.905643Z
addr = 0xb10420
size = 0x19e
name = "CCSPlayerController_Connect"
type = "long long"

[header]
name = "CCSPlayerController_Connect"
addr = 0xb10420
type = "long long"

[header.args]
