last_change = 2026-09-10T18:38:12.905672Z
addr = 0xb14e80
size = 0x49
name = "CBasePlayerPawn_EyeVectors"
type = "long long"

[header]
name = "CBasePlayerPawn_EyeVectors"
addr = 0xb14e80
type = "long long"

[header.args]
