last_change = 2026-09-10T18:38:12.905648Z
addr = 0xb11200
size = 0xc1
name = "CBaseModelEntity_DamageDecal"
type = "unsigned long long *"

[header]
name = "CBaseModelEntity_DamageDecal"
addr = 0xb11200
type = "unsigned long long *"

[header.args]
