last_change = 2026-09-10T18:38:12.905731Z
addr = 0xb2df90
size = 0x5fe
name = "CBasePlayerController_ProcessUsercmds"
type = "long long"

[header]
name = "CBasePlayerController_ProcessUsercmds"
addr = 0xb2df90
type = "long long"

[header.args]
