last_change = 2026-09-10T18:38:32.752663Z
addr = 0xb21d10
size = 0x64
name = "CBasePlayerController_IsFakeClient"
type = "char"

[header]
name = "CBasePlayerController_IsFakeClient"
addr = 0xb21d10
type = "char"

[header.args]
