last_change = 2026-09-10T18:38:12.905787Z
addr = 0xb3ab50
size = 0x3f0
name = "CBaseModelEntity_SetRenderAttribute"
type = "void"

[header]
name = "CBaseModelEntity_SetRenderAttribute"
addr = 0xb3ab50
type = "void"

[header.args]
