last_change = 2026-09-10T18:38:12.905735Z
addr = 0xb37620
size = 0x6b
name = "CBaseModelEntity_ScriptGetAttachmentAngles"

[header]
name = "CBaseModelEntity_ScriptGetAttachmentAngles"
addr = 0xb37620

[header.args]
