last_change = 2026-09-10T18:38:33.388014Z
addr = 0xb38400
size = 0x318
name = "CBasePlayerController_SetConnectedState"
type = "long long"

[header]
name = "CBasePlayerController_SetConnectedState"
addr = 0xb38400
type = "long long"

[header.args]
