last_change = 2026-09-10T18:38:12.905749Z
addr = 0xb377b0
size = 0x2f
name = "CBaseModelEntity_ScriptLookupAttachment"

[header]
name = "CBaseModelEntity_ScriptLookupAttachment"
addr = 0xb377b0

[header.args]
