last_change = 2026-09-10T18:38:12.905740Z
addr = 0xb37690
size = 0x47
name = "CBaseModelEntity_ScriptGetAttachmentForward"

[header]
name = "CBaseModelEntity_ScriptGetAttachmentForward"
addr = 0xb37690

[header.args]
