last_change = 2026-09-10T18:38:12.905777Z
addr = 0xb39fc0
size = 0x528
name = "CBasePlayerController_SetPawn"
type = "long long"

[header]
name = "CBasePlayerController_SetPawn"
addr = 0xb39fc0
type = "long long"

[header.args]
