last_change = 2026-09-10T18:38:12.905744Z
addr = 0xb376e0
size = 0x3b
name = "CBaseModelEntity_ScriptGetAttachmentOrigin"

[header]
name = "CBaseModelEntity_ScriptGetAttachmentOrigin"
addr = 0xb376e0

[header.args]
