last_change = 2026-09-10T18:38:12.905792Z
addr = 0xb6f740
size = 0x55
name = "CBaseFilter_InputTestActivator"
type = "long long"

[header]
name = "CBaseFilter_InputTestActivator"
addr = 0xb6f740
type = "long long"

[header.args]
