last_change = 2026-09-10T18:38:33.730074Z
addr = 0xb828c0
size = 0x22e
name = "CEntitySaveRestoreBlockHandler_PreSave"
type = "long long"

[header]
name = "CEntitySaveRestoreBlockHandler_PreSave"
addr = 0xb828c0
type = "long long"

[header.args]
