last_change = 2026-09-10T18:38:12.905812Z
addr = 0xb82af0
size = 0x153
name = "CEntitySaveRestoreBlockHandler_Save"
type = "char *"

[header]
name = "CEntitySaveRestoreBlockHandler_Save"
addr = 0xb82af0
type = "char *"

[header.args]
