last_change = 2026-09-10T18:38:12.905817Z
addr = 0xb82c50
size = 0x2e4
name = "CEntitySaveRestoreBlockHandler_WriteSaveHeaders"
type = "long long"

[header]
name = "CEntitySaveRestoreBlockHandler_WriteSaveHeaders"
addr = 0xb82c50
type = "long long"

[header.args]
