last_change = 2026-09-10T18:38:12.905802Z
addr = 0xb81b00
size = 0x5
name = "CGameSystemReallocatingFactory_CSource2EntitySystem_Init"
type = "char"

[header]
name = "CGameSystemReallocatingFactory_CSource2EntitySystem_Init"
addr = 0xb81b00
type = "char"

[header.args]
