last_change = 2026-09-10T18:38:12.905821Z
addr = 0xb82f50
size = 0x22f
name = "CEntitySaveRestoreBlockHandler_ReadRestoreHeaders"
type = "long long"

[header]
name = "CEntitySaveRestoreBlockHandler_ReadRestoreHeaders"
addr = 0xb82f50
type = "long long"

[header.args]
