last_change = 2026-09-10T18:38:34.239598Z
addr = 0xba3b50
size = 0x154
name = "CGameEntitySystem_BuildResourceManifest_ManifestNameOrGroupName"
type = "long long"

[header]
name = "CGameEntitySystem_BuildResourceManifest_ManifestNameOrGroupName"
addr = 0xba3b50
type = "long long"

[header.args]
