last_change = 2026-09-10T18:38:12.905860Z
addr = 0xba3610
size = 0x4b2
name = "CGameEntitySystem_BuildResourceManifest_KeyValuesVectors"
type = "long long"

[header]
name = "CGameEntitySystem_BuildResourceManifest_KeyValuesVectors"
addr = 0xba3610
type = "long long"

[header.args]
