last_change = 2026-09-10T18:38:12.905870Z
addr = 0xba6f90
size = 0x31
name = "UTIL_CreateEntityByName"
type = "long long"

[header]
name = "UTIL_CreateEntityByName"
addr = 0xba6f90
type = "long long"

[header.args]
