last_change = 2026-09-10T18:38:34.408738Z
addr = 0xbabd10
size = 0x158
name = "CEntitySaveRestoreBlockHandler_DoRestoreEntity"
type = "bool"

[header]
name = "CEntitySaveRestoreBlockHandler_DoRestoreEntity"
addr = 0xbabd10
type = "bool"

[header.args]
