last_change = 2026-09-10T18:38:34.324261Z
addr = 0xba6fd0
size = 0x216
name = "CLoadingSpawnGroup_CreateEntityToSpawn"
type = "long long"

[header]
name = "CLoadingSpawnGroup_CreateEntityToSpawn"
addr = 0xba6fd0
type = "long long"

[header.args]
