last_change = 2026-09-10T18:38:12.905900Z
addr = 0xbb4330
size = 0xe4
name = "CGameEntitySystem_FindEntityByName"
type = "long long"

[header]
name = "CGameEntitySystem_FindEntityByName"
addr = 0xbb4330
type = "long long"

[header.args]
