last_change = 2026-09-10T18:38:12.905909Z
addr = 0xbba130
size = 0x29
name = "LegacyGameEventListener"
type = "long long"

[header]
name = "LegacyGameEventListener"
addr = 0xbba130
type = "long long"

[header.args]
