last_change = 2026-09-10T18:38:12.905905Z
addr = 0xbb5820
size = 0x22a
name = "CGameEntitySystem_FindEntityProcedural"
type = "long long"

[header]
name = "CGameEntitySystem_FindEntityProcedural"
addr = 0xbb5820
type = "long long"

[header.args]
