last_change = 2026-09-10T18:38:12.905919Z
addr = 0xbbc3a0
size = 0x53
name = "CGameEventManager_Init"
type = "char"

[header]
name = "CGameEventManager_Init"
addr = 0xbbc3a0
type = "char"

[header.args]
