last_change = 2026-09-10T18:38:34.789384Z
addr = 0xbc9500
size = 0x99
name = "CGameEntitySystem_OnAddEntity"
type = "long long"

[header]
name = "CGameEntitySystem_OnAddEntity"
addr = 0xbc9500
type = "long long"

[header.args]
