last_change = 2026-09-10T18:38:12.905934Z
addr = 0xbc9c90
size = 0x3
name = "CEntitySystem_OnRemoveEntity"
type = "void"

[header]
name = "CEntitySystem_OnRemoveEntity"
addr = 0xbc9c90
type = "void"

[header.args]
