last_change = 2026-09-10T18:38:12.905943Z
addr = 0xbcc3e0
size = 0x223
name = "CGameSceneNode_PreInstanceSpawn"
type = "void"

[header]
name = "CGameSceneNode_PreInstanceSpawn"
addr = 0xbcc3e0
type = "void"

[header.args]
