last_change = 2026-09-10T18:38:35.001824Z
addr = 0xbd0db0
size = 0x215
name = "CSpawnGroupEntityFilterRegistrar_RegisterSpawnGroupEntityFilters"
type = "_UNKNOWN **"

[header]
name = "CSpawnGroupEntityFilterRegistrar_RegisterSpawnGroupEntityFilters"
addr = 0xbd0db0
type = "_UNKNOWN **"

[header.args]
