last_change = 2026-09-10T18:38:35.087154Z
addr = 0xbd8590
size = 0x2c3
name = "CEntitySaveRestoreBlockHandler_SaveInternal"
type = "char"

[header]
name = "CEntitySaveRestoreBlockHandler_SaveInternal"
addr = 0xbd8590
type = "char"

[header.args]
