last_change = 2026-09-10T18:38:35.688514Z
addr = 0xbedb30
size = 0x68
name = "CLoopModeFactory_CLoopModeGame_Shutdown"
type = "long long"

[header]
name = "CLoopModeFactory_CLoopModeGame_Shutdown"
addr = 0xbedb30
type = "long long"

[header.args]
