last_change = 2026-09-10T18:38:12.906041Z
addr = 0xbec890
size = 0x68
name = "NET_ReloadGameEvents_CommandHandler"
type = "long long"

[header]
name = "NET_ReloadGameEvents_CommandHandler"
addr = 0xbec890
type = "long long"

[header.args]
