last_change = 2026-09-10T18:38:12.906057Z
addr = 0xbedba0
size = 0x1c8
name = "CLoopModeFactory_CLoopModeGame_CreateLoopMode"
type = "unsigned long long *"

[header]
name = "CLoopModeFactory_CLoopModeGame_CreateLoopMode"
addr = 0xbedba0
type = "unsigned long long *"

[header.args]
