last_change = 2026-09-10T18:38:12.906046Z
addr = 0xbeda70
size = 0xb5
name = "CLoopModeFactory_CLoopModeGame_Init"
type = "char"

[header]
name = "CLoopModeFactory_CLoopModeGame_Init"
addr = 0xbeda70
type = "char"

[header.args]
