last_change = 2026-09-10T18:38:35.344915Z
addr = 0xbe2c10
size = 0x60d
name = "CEntity2SaveRestore_StreamEntitiesFromFile"
type = "long long"

[header]
name = "CEntity2SaveRestore_StreamEntitiesFromFile"
addr = 0xbe2c10
type = "long long"

[header.args]
