last_change = 2026-09-10T18:38:12.905972Z
addr = 0xbe0c40
size = 0x5e
name = "CGameEntitySystem_SortEntities"
type = "long long"

[header]
name = "CGameEntitySystem_SortEntities"
addr = 0xbe0c40
type = "long long"

[header.args]
