last_change = 2026-09-10T18:38:12.906077Z
addr = 0xbfdcb0
size = 0xbd
name = "DispatchParticleEffect2"
type = "long long"

[header]
name = "DispatchParticleEffect2"
addr = 0xbfdcb0
type = "long long"

[header.args]
