last_change = 2026-09-10T18:38:12.906087Z
addr = 0xbff470
size = 0x478
name = "CLoopModeGame_RegisterEventMapInternal"
type = "long long"

[header]
name = "CLoopModeGame_RegisterEventMapInternal"
addr = 0xbff470
type = "long long"

[header.args]
