last_change = 2026-09-10T18:38:12.906067Z
addr = 0xbfc470
size = 0x6b
name = "CLoopModeGame_AddViewsToSceneSystem"
type = "_OWORD *"

[header]
name = "CLoopModeGame_AddViewsToSceneSystem"
addr = 0xbfc470
type = "_OWORD *"

[header.args]
