last_change = 2026-09-10T18:38:12.906108Z
addr = 0xc0b570
size = 0xd0
name = "CLoopModeGame_OnFrameBoundary"
type = "long long"

[header]
name = "CLoopModeGame_OnFrameBoundary"
addr = 0xc0b570
type = "long long"

[header.args]
