last_change = 2026-09-10T18:38:36.068842Z
addr = 0xc08170
size = 0x12eb
name = "CLoopModeGame_LoopInit"
type = "char"

[header]
name = "CLoopModeGame_LoopInit"
addr = 0xc08170
type = "char"

[header.args]
