last_change = 2026-09-10T18:38:12.906144Z
addr = 0xc0bfb0
size = 0xd0
name = "CLoopModeGame_OnServerPostAdvanceTick"
type = "long long"

[header]
name = "CLoopModeGame_OnServerPostAdvanceTick"
addr = 0xc0bfb0
type = "long long"

[header.args]
