last_change = 2026-09-10T18:38:12.906154Z
addr = 0xc0d1f0
size = 0x4a1
name = "CLoopModeGame_ReceivedServerInfo"
type = "char"

[header]
name = "CLoopModeGame_ReceivedServerInfo"
addr = 0xc0d1f0
type = "char"

[header.args]
