last_change = 2026-09-10T18:38:12.906113Z
addr = 0xc0b640
size = 0x19d
name = "CLoopModeGame_OnLoopActivate"
type = "long long"

[header]
name = "CLoopModeGame_OnLoopActivate"
addr = 0xc0b640
type = "long long"

[header.args]
