last_change = 2026-09-10T18:38:12.906102Z
addr = 0xc09460
size = 0x162
name = "CLoopModeGame_ShutdownServer"
type = "void"

[header]
name = "CLoopModeGame_ShutdownServer"
addr = 0xc09460
type = "void"

[header.args]
