last_change = 2026-09-10T18:38:12.906176Z
addr = 0xc1eac0
size = 0x285
name = "CPlayer_MovementServices_ForceButtons"
type = "void"

[header]
name = "CPlayer_MovementServices_ForceButtons"
addr = 0xc1eac0
type = "void"

[header.args]
