last_change = 2026-09-10T18:38:36.752500Z
addr = 0xc29480
size = 0x4fb
name = "CCSPlayer_MovementServices_ProcessMovement"
type = "long long"

[header]
name = "CCSPlayer_MovementServices_ProcessMovement"
addr = 0xc29480
type = "long long"

[header.args]
