last_change = 2026-09-10T18:38:37.008774Z
addr = 0xc62170
size = 0x89b
name = "CSkeletonInstance_PostDataUpdate"
type = "int"

[header]
name = "CSkeletonInstance_PostDataUpdate"
addr = 0xc62170
type = "int"

[header.args]
