last_change = 2026-09-10T18:38:12.906226Z
addr = 0xc68b40
size = 0x48
name = "UTIL_PlayerSlotToPlayerPawn"
type = "long long"

[header]
name = "UTIL_PlayerSlotToPlayerPawn"
addr = 0xc68b40
type = "long long"

[header.args]
