last_change = 2026-09-10T18:38:12.906290Z
addr = 0xc7fad0
size = 0x35c
name = "EntInfo_CommandHandler"
type = "void"

[header]
name = "EntInfo_CommandHandler"
addr = 0xc7fad0
type = "void"

[header.args]
