last_change = 2026-09-10T18:38:12.906242Z
addr = 0xc744b0
size = 0x1dd
name = "CEntFireOutputAutoCompletionFunctor_FireOutput"
type = "long long"

[header]
name = "CEntFireOutputAutoCompletionFunctor_FireOutput"
addr = 0xc744b0
type = "long long"

[header.args]
