last_change = 2026-09-10T18:38:37.603512Z
addr = 0xc7f9a0
size = 0x121
name = "FireTarget_CommandHandler"
type = "void"

[header]
name = "FireTarget_CommandHandler"
addr = 0xc7f9a0
type = "void"

[header.args]
