last_change = 2026-09-10T18:38:37.264396Z
addr = 0xc76e40
size = 0x84d
name = "CBaseEntity_ctor"
type = "long long"

[header]
name = "CBaseEntity_ctor"
addr = 0xc76e40
type = "long long"

[header.args]
