last_change = 2026-09-10T18:38:12.906253Z
addr = 0xc78bb0
size = 0x1e9
name = "CBaseEntity_dtor"
type = "long long"

[header]
name = "CBaseEntity_dtor"
addr = 0xc78bb0
type = "long long"

[header.args]
