last_change = 2026-09-10T18:38:12.906279Z
addr = 0xc7c4c0
size = 0x3a
name = "CCSPlayerController_AddedToEntityDatabase"
type = "long long"

[header]
name = "CCSPlayerController_AddedToEntityDatabase"
addr = 0xc7c4c0
type = "long long"

[header.args]
