last_change = 2026-09-10T18:38:12.906300Z
addr = 0xc8d180
size = 0x189
name = "CBaseCombatCharacter_OnKilled"
type = "char"

[header]
name = "CBaseCombatCharacter_OnKilled"
addr = 0xc8d180
type = "char"

[header.args]
