last_change = 2026-09-10T18:38:37.648073Z
addr = 0xc8ae20
size = 0x17
name = "CBasePlayerPawn_DropActivePlayerWeapon"
type = "long long"

[header]
name = "CBasePlayerPawn_DropActivePlayerWeapon"
addr = 0xc8ae20
type = "long long"

[header.args]
