last_change = 2026-09-10T18:38:12.906333Z
addr = 0xc9efd0
size = 0x1f9
name = "CBaseEntity_OnSetDormant"
type = "long long"

[header]
name = "CBaseEntity_OnSetDormant"
addr = 0xc9efd0
type = "long long"

[header.args]
