last_change = 2026-09-10T18:38:12.906363Z
addr = 0xca5260
size = 0x3b
name = "CBaseEntity_ScriptGetLocalAngularVelocity_OBSOLETE"

[header]
name = "CBaseEntity_ScriptGetLocalAngularVelocity_OBSOLETE"
addr = 0xca5260

[header.args]
