last_change = 2026-09-10T18:38:12.906398Z
addr = 0xca5460
size = 0x26
name = "CBaseEntity_ScriptSetLocalAngularVelocity_OBSOLETE"

[header]
name = "CBaseEntity_ScriptSetLocalAngularVelocity_OBSOLETE"
addr = 0xca5460

[header.args]
