last_change = 2026-09-10T18:38:12.906381Z
addr = 0xca53a0
size = 0x3c
name = "CBaseEntity_ScriptGetRootMoveParent"

[header]
name = "CBaseEntity_ScriptGetRootMoveParent"
addr = 0xca53a0

[header.args]
