last_change = 2026-09-10T18:38:12.906420Z
addr = 0xca5710
size = 0x24
name = "CBaseEntity_Script_ApplyLocalAngularVelocityImpulse"

[header]
name = "CBaseEntity_Script_ApplyLocalAngularVelocityImpulse"
addr = 0xca5710

[header.args]
