last_change = 2026-09-10T18:38:12.906453Z
addr = 0xcb1960
size = 0x5d8
name = "CMomentaryRotButton_Use"
type = "double"

[header]
name = "CMomentaryRotButton_Use"
addr = 0xcb1960
type = "double"

[header.args]
