last_change = 2026-09-10T18:38:12.906493Z
addr = 0xd41ad0
size = 0x84
name = "CGameRulesGameSystem_OnGameShutdown"
type = "void"

[header]
name = "CGameRulesGameSystem_OnGameShutdown"
addr = 0xd41ad0
type = "void"

[header.args]
