last_change = 2026-09-10T18:38:12.906483Z
addr = 0xd411e0
size = 0x93
name = "CSource2GameEntities_ShouldClientReceiveStringTableUserData"
type = "char"

[header]
name = "CSource2GameEntities_ShouldClientReceiveStringTableUserData"
addr = 0xd411e0
type = "char"

[header.args]
