last_change = 2026-09-10T18:38:12.906522Z
addr = 0xd436f0
size = 0xf1
name = "CSource2Server_WriteSignonMessages"
type = "long long"

[header]
name = "CSource2Server_WriteSignonMessages"
addr = 0xd436f0
type = "long long"

[header.args]
