last_change = 2026-09-10T18:38:12.906600Z
addr = 0xd4c840
size = 0x19e
name = "CSource2GameClients_ClientActive"
type = "long long"

[header]
name = "CSource2GameClients_ClientActive"
addr = 0xd4c840
type = "long long"

[header.args]
