last_change = 2026-09-10T18:38:12.906595Z
addr = 0xd46030
size = 0xd5
name = "CSource2Server_OnStreamEntitiesFromFileCompleted"

[header]
name = "CSource2Server_OnStreamEntitiesFromFileCompleted"
addr = 0xd46030

[header.args]
