last_change = 2026-09-10T18:38:39.813013Z
addr = 0xd43910
size = 0xbb
name = "CSource2Server_GetLevelsFromSaveFile"
type = "void"

[header]
name = "CSource2Server_GetLevelsFromSaveFile"
addr = 0xd43910
type = "void"

[header.args]
