last_change = 2026-09-10T18:38:12.906638Z
addr = 0xd4e180
size = 0x26
name = "CSource2GameClients_ClientSettingsChanged"
type = "long long"

[header]
name = "CSource2GameClients_ClientSettingsChanged"
addr = 0xd4e180
type = "long long"

[header.args]
