last_change = 2026-09-10T18:38:12.906614Z
addr = 0xd4cf20
size = 0x766
name = "CSource2GameClients_ClientDiagnostic"
type = "long long"

[header]
name = "CSource2GameClients_ClientDiagnostic"
addr = 0xd4cf20
type = "long long"

[header.args]
