last_change = 2026-09-10T18:38:12.906619Z
addr = 0xd4d690
size = 0x323
name = "CSource2GameClients_ClientDisconnect"
type = "long long"

[header]
name = "CSource2GameClients_ClientDisconnect"
addr = 0xd4d690
type = "long long"

[header.args]
