last_change = 2026-09-10T18:38:12.906609Z
addr = 0xd4ce60
size = 0xbb
name = "CSource2GameClients_ClientConnect"
type = "char"

[header]
name = "CSource2GameClients_ClientConnect"
addr = 0xd4ce60
type = "char"

[header.args]
