last_change = 2026-09-10T18:38:12.906605Z
addr = 0xd4cce0
size = 0x137
name = "CSource2GameClients_ClientCommand"
type = "void"

[header]
name = "CSource2GameClients_ClientCommand"
addr = 0xd4cce0
type = "void"

[header.args]
