last_change = 2026-09-10T18:38:12.906634Z
addr = 0xd4ded0
size = 0x2ac
name = "CGameRules_ClientSettingsChanged"
type = "long long"

[header]
name = "CGameRules_ClientSettingsChanged"
addr = 0xd4ded0
type = "long long"

[header.args]
