last_change = 2026-09-10T18:38:12.906624Z
addr = 0xd4da20
size = 0x1f5
name = "CSource2GameClients_ClientFullyConnect"
type = "void"

[header]
name = "CSource2GameClients_ClientFullyConnect"
addr = 0xd4da20
type = "void"

[header.args]
