last_change = 2026-09-10T18:38:12.906503Z
addr = 0xd432f0
size = 0x1f4
name = "CSource2Server_Init"
type = "long long"

[header]
name = "CSource2Server_Init"
addr = 0xd432f0
type = "long long"

[header.args]
