last_change = 2026-09-10T18:38:12.906585Z
addr = 0xd45790
size = 0x14b
name = "CSource2Server_BroadcastServerFrameTime"
type = "long long"

[header]
name = "CSource2Server_BroadcastServerFrameTime"
addr = 0xd45790
type = "long long"

[header.args]
