last_change = 2026-09-10T18:38:39.515150Z
addr = 0xd42e10
size = 0x47c
name = "CSource2Server_Connect"
type = "char"

[header]
name = "CSource2Server_Connect"
addr = 0xd42e10
type = "char"

[header.args]
