last_change = 2026-09-10T18:38:12.906658Z
addr = 0xd507d0
size = 0x1d3
name = "CSource2GameClients_GetBugReportInfo"
type = "int"

[header]
name = "CSource2GameClients_GetBugReportInfo"
addr = 0xd507d0
type = "int"

[header.args]
