last_change = 2026-09-10T18:38:41.086869Z
addr = 0xd574e0
size = 0x89b
name = "CSource2GameClients_ProcessUsercmds"
type = "long long"

[header]
name = "CSource2GameClients_ProcessUsercmds"
addr = 0xd574e0
type = "long long"

[header.args]
