last_change = 2026-09-10T18:38:12.906692Z
addr = 0xd5b950
size = 0x9f
name = "CSource2GameClients_StartHLTVServer"
type = "void"

[header]
name = "CSource2GameClients_StartHLTVServer"
addr = 0xd5b950
type = "void"

[header.args]
