last_change = 2026-09-10T18:38:12.906687Z
addr = 0xd59d90
size = 0x10a
name = "CGameRules_SetGamePaused"
type = "long long"

[header]
name = "CGameRules_SetGamePaused"
addr = 0xd59d90
type = "long long"

[header.args]
