last_change = 2026-09-10T18:38:12.906667Z
addr = 0xd51310
size = 0x93
name = "CGameRules_GetSaveGameComment"
type = "CUtlString *"

[header]
name = "CGameRules_GetSaveGameComment"
addr = 0xd51310
type = "CUtlString *"

[header.args]
