last_change = 2026-09-10T18:38:12.906662Z
addr = 0xd509b0
size = 0x6c
name = "CGameRules_GetChatPrefix"
type = "const char *"

[header]
name = "CGameRules_GetChatPrefix"
addr = 0xd509b0
type = "const char *"

[header.args]
