last_change = 2026-09-10T18:38:12.906697Z
addr = 0xd73e30
size = 0xd3
name = "CGamePlayerEquip_InputTriggerForActivatedPlayer"
type = "void"

[header]
name = "CGamePlayerEquip_InputTriggerForActivatedPlayer"
addr = 0xd73e30
type = "void"

[header.args]
