last_change = 2026-09-10T18:38:41.341251Z
addr = 0xd8a6e0
size = 0x195
name = "CMultiplayRules_ctor"
type = "unsigned long long *"

[header]
name = "CMultiplayRules_ctor"
addr = 0xd8a6e0
type = "unsigned long long *"

[header.args]
