last_change = 2026-09-10T18:38:12.906713Z
addr = 0xd930d0
size = 0x71
name = "CMultiplayRules_ClientDisconnected"
type = "long long"

[header]
name = "CMultiplayRules_ClientDisconnected"
addr = 0xd930d0
type = "long long"

[header.args]
