last_change = 2026-09-10T18:38:12.906718Z
addr = 0xd99f10
size = 0x18e
name = "CRagdollProp_DrawEntityDebugOverlays"
type = "long long"

[header]
name = "CRagdollProp_DrawEntityDebugOverlays"
addr = 0xd99f10
type = "long long"

[header.args]
