last_change = 2026-09-10T18:38:12.906723Z
addr = 0xdafc90
size = 0x16e
name = "PhysCollisionDust"
type = "float *"

[header]
name = "PhysCollisionDust"
addr = 0xdafc90
type = "float *"

[header.args]
