last_change = 2026-09-10T18:38:41.679800Z
addr = 0xdbdd60
size = 0xf6
name = "CBaseEntity_VPhysicsStartTouch"
type = "long long"

[header]
name = "CBaseEntity_VPhysicsStartTouch"
addr = 0xdbdd60
type = "long long"

[header.args]
