last_change = 2026-09-10T18:38:12.906727Z
addr = 0xdb2070
size = 0x34
name = "CBaseEntity_PhysicsTouch"
type = "long long"

[header]
name = "CBaseEntity_PhysicsTouch"
addr = 0xdb2070
type = "long long"

[header.args]
