last_change = 2026-09-10T18:38:41.850888Z
addr = 0xdda3f0
size = 0x5ea
name = "CPointTeleportAPI_TeleportEntityInternal"
type = "long long"

[header]
name = "CPointTeleportAPI_TeleportEntityInternal"
addr = 0xdda3f0
type = "long long"

[header.args]
