last_change = 2026-09-10T18:38:12.906751Z
addr = 0xdd3100
size = 0x38
name = "CPhysExplosion_Activate"
type = "long long"

[header]
name = "CPhysExplosion_Activate"
addr = 0xdd3100
type = "long long"

[header.args]
