last_change = 2026-09-10T18:38:42.021345Z
addr = 0xdf4c20
size = 0x25a
name = "CPlayerCommandQueue_UpdateStats"
type = "void"

[header]
name = "CPlayerCommandQueue_UpdateStats"
addr = 0xdf4c20
type = "void"

[header.args]
