last_change = 2026-09-10T18:38:12.906808Z
addr = 0xe8f6d0
size = 0x3eb
name = "CScriptedSequence_SynchronizeSequence"
type = "void"

[header]
name = "CScriptedSequence_SynchronizeSequence"
addr = 0xe8f6d0
type = "void"

[header.args]
