last_change = 2026-09-10T18:38:12.906813Z
addr = 0xeb1cd0
size = 0x36
name = "CTriggerGravity_GetTouchFunction"
type = "long long (__fastcall *)()"

[header]
name = "CTriggerGravity_GetTouchFunction"
addr = 0xeb1cd0
type = "long long (__fastcall *)()"

[header.args]
