last_change = 2026-09-10T18:38:12.906823Z
addr = 0xeb50d0
size = 0x3b
name = "CTriggerGravity_GravityTouch"
type = "long long"

[header]
name = "CTriggerGravity_GravityTouch"
addr = 0xeb50d0
type = "long long"

[header.args]
