last_change = 2026-09-10T18:38:12.906841Z
addr = 0xeced20
size = 0x1e2
name = "UTIL_SayTextFilter"
type = "long long"

[header]
name = "UTIL_SayTextFilter"
addr = 0xeced20
type = "long long"

[header.args]
