last_change = 2026-09-10T18:38:12.906832Z
addr = 0xecd510
size = 0x9e
name = "UTIL_ClientPrintAll"
type = "long long"

[header]
name = "UTIL_ClientPrintAll"
addr = 0xecd510
type = "long long"

[header.args]
