last_change = 2026-09-10T18:38:42.615009Z
addr = 0x123c4d0
size = 0x47
name = "CLoopModeRegistry_UnregisterLoopModes"
type = "long long"

[header]
name = "CLoopModeRegistry_UnregisterLoopModes"
addr = 0x123c4d0
type = "long long"

[header.args]
