last_change = 2026-09-10T18:38:43.379521Z
addr = 0x124c100
size = 0x1b5
name = "CEntitySystem_DestroyEntityImmediate"
type = "void"

[header]
name = "CEntitySystem_DestroyEntityImmediate"
addr = 0x124c100
type = "void"

[header.args]
