last_change = 2026-09-10T18:38:12.906864Z
addr = 0x1246340
size = 0x19c
name = "CEntitySystem_Activate"
type = "char"

[header]
name = "CEntitySystem_Activate"
addr = 0x1246340
type = "char"

[header.args]
