last_change = 2026-09-10T18:38:12.906918Z
addr = 0x124a8b0
size = 0x7e
name = "CEntitySystem_CreateEntitySystem"
type = "long long"

[header]
name = "CEntitySystem_CreateEntitySystem"
addr = 0x124a8b0
type = "long long"

[header.args]
