last_change = 2026-09-10T18:38:12.906878Z
addr = 0x1246710
size = 0x277
name = "CEntitySystem_AddEntityIOEvent"
type = "long long"

[header]
name = "CEntitySystem_AddEntityIOEvent"
addr = 0x1246710
type = "long long"

[header.args]
