last_change = 2026-09-10T18:38:43.294739Z
addr = 0x124c000
size = 0xdb
name = "CEntitySystem_DestroyEntity"
type = "long long"

[header]
name = "CEntitySystem_DestroyEntity"
addr = 0x124c000
type = "long long"

[header.args]
