last_change = 2026-09-10T18:38:42.827195Z
addr = 0x1246500
size = 0x205
name = "CEntitySystem_AddEntityIOEventToQueue"
type = "void"

[header]
name = "CEntitySystem_AddEntityIOEventToQueue"
addr = 0x1246500
type = "void"

[header.args]
