last_change = 2026-09-10T18:38:42.784210Z
addr = 0x12464e0
size = 0x1c
name = "CEntitySystem_RegisterAccessor"
type = "long long"

[header]
name = "CEntitySystem_RegisterAccessor"
addr = 0x12464e0
type = "long long"

[header.args]
