last_change = 2026-09-10T18:38:42.993733Z
addr = 0x12472c0
size = 0x279
name = "CEntitySystem_AddEntityToNameMap"
type = "void"

[header]
name = "CEntitySystem_AddEntityToNameMap"
addr = 0x12472c0
type = "void"

[header.args]
