last_change = 2026-09-10T18:38:43.121268Z
addr = 0x1248ba0
size = 0x2bd
name = "CEntitySystem_PrecacheEntity"
type = "long long"

[header]
name = "CEntitySystem_PrecacheEntity"
addr = 0x1248ba0
type = "long long"

[header.args]
