last_change = 2026-09-10T18:38:12.907088Z
addr = 0x125d4f0
size = 0x382
name = "CEntityIOOutput_FireOutputInternal"
type = "long long"

[header]
name = "CEntityIOOutput_FireOutputInternal"
addr = 0x125d4f0
type = "long long"

[header.args]
