last_change = 2026-09-10T18:38:12.907083Z
addr = 0x125cfd0
size = 0x130
name = "CEntitySystem_UpdateOnRemove"
type = "char"

[header]
name = "CEntitySystem_UpdateOnRemove"
addr = 0x125cfd0
type = "char"

[header.args]
