last_change = 2026-09-10T18:38:12.907008Z
addr = 0x12550e0
size = 0x89
name = "CEntitySystem_AddEntityToEntityDataBase"
type = "long long"

[header]
name = "CEntitySystem_AddEntityToEntityDataBase"
addr = 0x12550e0
type = "long long"

[header.args]
