last_change = 2026-09-10T18:38:43.899506Z
addr = 0x1250e30
size = 0x5d9
name = "CEntitySystem_HelperExecuteQueuedSpawn"
type = "int"

[header]
name = "CEntitySystem_HelperExecuteQueuedSpawn"
addr = 0x1250e30
type = "int"

[header.args]
