last_change = 2026-09-10T18:38:12.907030Z
addr = 0x12559d0
size = 0xb5
name = "CEntitySystem_QueueDestroyEntity"
type = "void"

[header]
name = "CEntitySystem_QueueDestroyEntity"
addr = 0x12559d0
type = "void"

[header.args]
