last_change = 2026-09-10T18:38:43.857076Z
addr = 0x1250c40
size = 0x1a
name = "CEntityKeyValuesAllocator_GetTempBuffer"
type = "__int128 *"

[header]
name = "CEntityKeyValuesAllocator_GetTempBuffer"
addr = 0x1250c40
type = "__int128 *"

[header.args]
