last_change = 2026-09-10T18:38:12.907017Z
addr = 0x12551f0
size = 0x4f
name = "CEntitySystem_OnSetDormant"
type = "long long"

[header]
name = "CEntitySystem_OnSetDormant"
addr = 0x12551f0
type = "long long"

[header.args]
