last_change = 2026-09-10T18:38:12.907099Z
addr = 0x125fde0
size = 0x18b
name = "CEntityKeyValues_LoadFromContext"
type = "char"

[header]
name = "CEntityKeyValues_LoadFromContext"
addr = 0x125fde0
type = "char"

[header.args]
