last_change = 2026-09-10T18:38:44.535872Z
addr = 0x125a7f0
size = 0x25a
name = "CEntitySystem_SetInPVS"
type = "void"

[header]
name = "CEntitySystem_SetInPVS"
addr = 0x125a7f0
type = "void"

[header.args]
