last_change = 2026-09-10T18:38:12.907182Z
addr = 0x126f410
size = 0x12d
name = "CEntityIdentity_SetEntityName"
type = "long long"

[header]
name = "CEntityIdentity_SetEntityName"
addr = 0x126f410
type = "long long"

[header.args]
