last_change = 2026-09-10T18:38:12.907113Z
addr = 0x126b290
size = 0x7
name = "CEntityInstance_PostDataUpdateDelta"
type = "long long"

[header]
name = "CEntityInstance_PostDataUpdateDelta"
addr = 0x126b290
type = "long long"

[header.args]
