last_change = 2026-09-10T18:38:12.907177Z
addr = 0x126e750
size = 0xcf
name = "CEntityIdentity_FreeAttributes"
type = "void"

[header]
name = "CEntityIdentity_FreeAttributes"
addr = 0x126e750
type = "void"

[header.args]
