last_change = 2026-09-10T18:38:45.300512Z
addr = 0x126df80
size = 0xa
name = "CEntityInstance_NetworkUpdateState_thunk"
type = "long long"

[header]
name = "CEntityInstance_NetworkUpdateState_thunk"
addr = 0x126df80
type = "long long"

[header.args]
