last_change = 2026-09-10T18:38:12.907108Z
addr = 0x126aad0
size = 0x73
name = "CEntityInstance_AcceptInput"
type = "long long"

[header]
name = "CEntityInstance_AcceptInput"
addr = 0x126aad0
type = "long long"

[header.args]
