last_change = 2026-09-10T18:38:45.088266Z
addr = 0x126c5d0
size = 0x1c3
name = "CBaseEntity_ReloadPrivateScripts"
type = "void"

[header]
name = "CBaseEntity_ReloadPrivateScripts"
addr = 0x126c5d0
type = "void"

[header.args]
