last_change = 2026-09-10T18:38:12.907128Z
addr = 0x126c050
size = 0x5
name = "CEntityInstance_GetScriptDesc"
type = "long long"

[header]
name = "CEntityInstance_GetScriptDesc"
addr = 0x126c050
type = "long long"

[header.args]
