last_change = 2026-09-10T18:38:45.383489Z
addr = 0x126e020
size = 0x433
name = "CEntityIdentity_AcceptInputInternal"
type = "char"

[header]
name = "CEntityIdentity_AcceptInputInternal"
addr = 0x126e020
type = "char"

[header.args]
